# Generated by Django 4.2.20 on 2025-05-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_url_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
