# Generated by Django 4.2.20 on 2025-05-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotion_is_archived_alter_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
