# Generated by Django 4.2.20 on 2025-05-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly', '月訂閱'), ('yearly', '年訂閱')], max_length=10)),
                ('amount', models.IntegerField()),
                ('interval_days', models.IntegerField()),
            ],
        ),
    ]
