# Generated by Django 4.2.20 on 2025-05-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_name',
        ),
    ]
