# Generated by Django 4.2.20 on 2025-05-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentorder_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='interval_days',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.product'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
