# Generated by Django 4.2.20 on 2025-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=10),
        ),
    ]
