# Generated by Django 4.2.20 on 2025-06-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentorder_transaction_id_alter_product_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('return_code', models.CharField(max_length=10)),
                ('return_message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.paymentorder')),
            ],
        ),
    ]
