# Generated by Django 4.2.20 on 2025-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('ecpay', '綠界'), ('linepay', 'LINE Pay')], default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='method',
            field=models.CharField(choices=[('ecpay', '綠界'), ('linepay', 'LINE Pay')], default='null', max_length=20),
        ),
    ]
