# Generated by Django 4.2.20 on 2025-05-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_merchant',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', '一般會員'), ('merchant', '商家'), ('vip_merchant', 'VIP 商家')], default='member', max_length=20),
        ),
    ]
