# Generated by Django 4.2.20 on 2025-05-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_img_url_user_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
